id: P006647
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD159408
  title: མཚོ་སྣ་བ་སྟོབས་རྒྱལ་གྱི་དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    33a6cf05d0ae45ae8584e6b73480da61:
      image_group_id: I2PD18973
      title: ''
      volume_number: 1
      total_pages: 728
      base_file: v001.txt
